// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7t44PiKZxjj3FKBnFzGJFd57e74NoKmU',
    appId: '1:367018379109:web:f3277440d35b4279c3038c',
    messagingSenderId: '367018379109',
    projectId: 'hello-world-82363',
    authDomain: 'hello-world-82363.firebaseapp.com',
    storageBucket: 'hello-world-82363.appspot.com',
    measurementId: 'G-M27505FCX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0zInXd3JDPWJX8xB0YPH4NNX9xPB1lo',
    appId: '1:367018379109:android:e2f781dab10a42f4c3038c',
    messagingSenderId: '367018379109',
    projectId: 'hello-world-82363',
    storageBucket: 'hello-world-82363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAan39EYKvfLkgsf_ZMJlelcmNtE96lLIo',
    appId: '1:367018379109:ios:31149a7f3cf16293c3038c',
    messagingSenderId: '367018379109',
    projectId: 'hello-world-82363',
    storageBucket: 'hello-world-82363.appspot.com',
    iosClientId: '367018379109-5kau0pa90imk7irek542df31fs1241l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAan39EYKvfLkgsf_ZMJlelcmNtE96lLIo',
    appId: '1:367018379109:ios:31149a7f3cf16293c3038c',
    messagingSenderId: '367018379109',
    projectId: 'hello-world-82363',
    storageBucket: 'hello-world-82363.appspot.com',
    iosClientId: '367018379109-5kau0pa90imk7irek542df31fs1241l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskTracker',
  );
}
